name: notworthit
on:
  issues:
    types:
      - labeled
jobs:
  add-comment:
    if: github.event.label.name == 'not-worth-it'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          close-reason: not_planned
          comment: Thanks for the support, but not every normal domain will be excluded/allowed. In principle, only popular legal domains that have been on relevant top lists (Umbrella, Cloudflare, Tranco, Chrome, DomCop, ...) in the last 12 months or disrupt the functionality of popular apps, websites or services are excluded. No illegal domains, e.g. from the piracy category, will be unblocked.<br>If this requirement is not met, it will be decided on a case-by-case basis whether the domains will be excluded.<br>In this case, it was decided that it is not worth excluding the domain.<br>Allowing must be done in the personal allowlist.<br><br>The reason for this procedure is that the length of the denyallow/domain modifier in lists formatted for AdGuard or uBlock is limited before the rule becomes invalid. This means that if every normal domain of the corresponding TLD were to be excluded, important rules would become invalid at some point. It must therefore be carefully weighed up what is excluded and what is not.
